TItaPR/TItaPR/Controllers/CriteriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TItaPR.DBContext;
using TItaPR.Models.Entity;

namespace TItaPR.Controllers
{
    public class CriteriaController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Criteria
        public ActionResult Index()
        {
            return View(db.Criterions.ToList());
        }

        // GET: Criteria/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criterion criterion = db.Criterions.Find(id);
            if (criterion == null)
            {
                return HttpNotFound();
            }
            return View(criterion);
        }

        // GET: Criteria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Criteria/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CNum,CName,CRange,CWeight,CType,OptimType,EdIzmer,ScaleType")] Criterion criterion)
        {
            if (ModelState.IsValid)
            {
                db.Criterions.Add(criterion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(criterion);
        }

        // GET: Criteria/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criterion criterion = db.Criterions.Find(id);
            if (criterion == null)
            {
                return HttpNotFound();
            }
            return View(criterion);
        }

        // POST: Criteria/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CNum,CName,CRange,CWeight,CType,OptimType,EdIzmer,ScaleType")] Criterion criterion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(criterion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(criterion);
        }

        // GET: Criteria/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criterion criterion = db.Criterions.Find(id);
            if (criterion == null)
            {
                return HttpNotFound();
            }
            return View(criterion);
        }

        // POST: Criteria/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Criterion criterion = db.Criterions.Find(id);
            db.Criterions.Remove(criterion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TItaPR/TItaPR/Controllers/LPRsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TItaPR.DBContext;
using TItaPR.Models.Entity;

namespace TItaPR.Controllers
{
    public class LPRsController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: LPRs
        public ActionResult Index()
        {
            return View(db.LPRs.ToList());
        }

        // GET: LPRs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LPR lPR = db.LPRs.Find(id);
            if (lPR == null)
            {
                return HttpNotFound();
            }
            return View(lPR);
        }

        // GET: LPRs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LPRs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LNum,Lname,LRange")] LPR lPR)
        {
            if (ModelState.IsValid)
            {
                db.LPRs.Add(lPR);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lPR);
        }

        // GET: LPRs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LPR lPR = db.LPRs.Find(id);
            if (lPR == null)
            {
                return HttpNotFound();
            }
            return View(lPR);
        }

        // POST: LPRs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LNum,Lname,LRange")] LPR lPR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lPR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lPR);
        }

        // GET: LPRs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LPR lPR = db.LPRs.Find(id);
            if (lPR == null)
            {
                return HttpNotFound();
            }
            return View(lPR);
        }

        // POST: LPRs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LPR lPR = db.LPRs.Find(id);
            db.LPRs.Remove(lPR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SelectUser(int userId)
        {
            Session["CurrentUserId"] = userId;
            var user = db.LPRs.Find(userId);
            Session["CurrentUserName"] = user.Lname;
            return RedirectToAction("Index", "Alternatives");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

TItaPR/TItaPR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Users", "Index", "LPRs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (@Session["CurrentUserName"] != null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Alternatives", "Index", "Alternatives")</li>
                        <li>@Html.ActionLink("Criterials", "Index", "Criteria")</li>
                        <li>@Html.ActionLink("Marks", "Index", "Marks")</li>
                        <li>@Html.ActionLink("Results", "ShowResults", "Home")</li>
                        <li>@Html.ActionLink("Vectors", "Index", "Vectors")</li>
                        <li>@Html.ActionLink("MaxMinMethod", "MaxMinMethod", "Home")</li>
                        <li>@Html.ActionLink("Election", "About", "Home")</li>
                        
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink(@Session["CurrentUserName"].ToString(), "Index", "LPRs")
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>